server:
  port: 8010    #port number
  
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
          
spring:   
  application:
    name: api-gateway  
  boot:
    admin:
       client:
          url: http://localhost:8761/admin   
         
logging:
  level:
    com.example.howtodoinjava: DEBUG